### ISSUE TITLE
Test modules are not importing environment variables

### ISSUE THREAD

**Issue by ascension2020** [InsightSSG/Net-Manage#447]
The test modules, like test/test_cisco_ios_collectors.py, are not importing environment variables correctly.

Files to correct:

- [x] test/test_cisco_ios_collectors.py - commit f7243beff258f36e1a961527dbb5b8ad6bd66624
- [x] test_cisco_nxos_collectors.py
- [x] test_f5_collectors.py
- [x] test_meraki_collectors.py
- [x] test_palo_alto_collectors.py

**Comment by petecory** [comment]
I reviewed the Meraki Test and it looks to be correct already, no changes have been made to it. All others have been complete with the Palo updates pending review.
